# Generated by Django 4.2.7 on 2023-11-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utc_date", models.DateField()),
                ("equipment", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Observatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iau_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_id", models.CharField(max_length=100)),
                ("tic_id", models.CharField(max_length=30)),
                ("gaia_id", models.CharField(max_length=30)),
                ("ra", models.FloatField(verbose_name="RA(2000)")),
                ("dec", models.FloatField(verbose_name="Dec(2000)")),
            ],
        ),
        migrations.CreateModel(
            name="ScienceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("uri", models.CharField(max_length=200)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tom.target"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="observatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tom.observatory"
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tom.target"
            ),
        ),
    ]
