# Generated by Django 4.2.7 on 2023-11-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RawData",
            new_name="PhotometryRawData",
        ),
        migrations.AddField(
            model_name="scienceresult",
            name="author",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="target",
            name="local_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="SpectrumRawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeckleRawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                ("gain", models.PositiveIntegerField()),
                ("exposure_time_ms", models.PositiveIntegerField()),
                ("num_sequences", models.PositiveIntegerField()),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherRawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
