# Generated by Django 4.2.7 on 2023-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlist",
            name="targets",
            field=models.ManyToManyField(to="tom.target"),
        ),
        migrations.DeleteModel(
            name="TargetListMember",
        ),
    ]
