# Generated by Django 4.2.7 on 2023-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0002_targetlist_targets_delete_targetlistmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetlist",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
