# Generated by Django 4.2.7 on 2023-11-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0002_rename_rawdata_photometryrawdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("affiliation", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="observatory",
            name="nickname",
            field=models.CharField(default="APO", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="target",
            name="distance",
            field=models.FloatField(default=10, verbose_name="Distance (pc)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="target",
            name="pmdec",
            field=models.FloatField(default=0, verbose_name="PM Dec (mas/yr)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="target",
            name="pmra",
            field=models.FloatField(default=0, verbose_name="PM RA (mas/yr)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="target",
            name="dec",
            field=models.FloatField(verbose_name="Dec(2000) (deg)"),
        ),
        migrations.AlterField(
            model_name="target",
            name="ra",
            field=models.FloatField(verbose_name="RA(2000) (deg)"),
        ),
        migrations.CreateModel(
            name="Observer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tom.person"
                    ),
                ),
            ],
        ),
    ]
