# Generated by Django 4.2.7 on 2023-11-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0003_person_observatory_nickname_target_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("Speckle Imaging", "Speckle Imaging"),
                    ("Spectroscopy", "Spectroscopy"),
                    ("Photometry", "Photometry"),
                    ("Other", "Other"),
                ],
                default="Speckle Imaging",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="target",
            name="dec",
            field=models.FloatField(verbose_name="Dec (deg)"),
        ),
        migrations.AlterField(
            model_name="target",
            name="ra",
            field=models.FloatField(verbose_name="RA (deg)"),
        ),
    ]
