# Generated by Django 4.2.7 on 2023-12-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0003_alter_targetlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlist",
            name="description",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
    ]
