# Generated by Django 4.2.7 on 2023-11-16 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0005_observationpurpose_alter_observation_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otherrawdata",
            name="size",
        ),
        migrations.RemoveField(
            model_name="photometryrawdata",
            name="size",
        ),
        migrations.RemoveField(
            model_name="specklerawdata",
            name="size",
        ),
        migrations.RemoveField(
            model_name="spectrumrawdata",
            name="size",
        ),
    ]
