# Generated by Django 4.2.7 on 2023-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0006_remove_spectrumrawdata_jd_btd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingsession",
            name="equipment",
            field=models.CharField(
                help_text="Format: <telescope>+<instrument>", max_length=200
            ),
        ),
    ]
