# Generated by Django 4.2.7 on 2023-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0007_alter_observingsession_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="specklerawdata",
            name="channels",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
