# Generated by Django 4.2.7 on 2023-11-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0007_target_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="magnitude",
            field=models.FloatField(default=0, verbose_name="V-mag"),
        ),
    ]
