# Generated by Django 4.2.7 on 2023-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0008_target_magnitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observatory",
            options={"verbose_name_plural": "Observatories"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.AddField(
            model_name="scienceresult",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
    ]
