# Generated by Django 4.2.7 on 2023-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0009_alter_observatory_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otherrawdata",
            options={"verbose_name_plural": "Other Raw Data"},
        ),
        migrations.AlterModelOptions(
            name="photometryrawdata",
            options={"verbose_name_plural": "Photometry Raw Data"},
        ),
        migrations.AlterModelOptions(
            name="specklerawdata",
            options={"verbose_name_plural": "Speckle Raw Data"},
        ),
        migrations.AlterModelOptions(
            name="spectrumrawdata",
            options={"verbose_name_plural": "Spectrum Raw Data"},
        ),
        migrations.AddField(
            model_name="observation",
            name="observers",
            field=models.ManyToManyField(to="tom.person"),
        ),
        migrations.DeleteModel(
            name="Observer",
        ),
    ]
