# Generated by Django 4.2.7 on 2023-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0010_alter_otherrawdata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scienceresult",
            name="author",
        ),
        migrations.AddField(
            model_name="scienceresult",
            name="author",
            field=models.ManyToManyField(blank=True, to="tom.person"),
        ),
    ]
