# Generated by Django 4.2.7 on 2023-12-20 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tom",
            "0010_rename_observing_program_observingsession_observingprogram_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="specklerawdata",
            old_name="channels",
            new_name="channel",
        ),
        migrations.RemoveField(
            model_name="specklerawdata",
            name="num_sequences",
        ),
    ]
