# Generated by Django 4.2.7 on 2023-11-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0012_alter_person_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observatory",
            options={},
        ),
        migrations.AlterModelOptions(
            name="otherrawdata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={},
        ),
        migrations.AlterModelOptions(
            name="photometryrawdata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="specklerawdata",
            options={},
        ),
        migrations.AlterModelOptions(
            name="spectrumrawdata",
            options={},
        ),
        migrations.RemoveField(
            model_name="observation",
            name="observers",
        ),
        migrations.RemoveField(
            model_name="scienceresult",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="target",
            name="magnitude",
        ),
        migrations.AddField(
            model_name="otherrawdata",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photometryrawdata",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specklerawdata",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="spectrumrawdata",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="target",
            name="calibrations",
            field=models.ManyToManyField(to="tom.target"),
        ),
        migrations.AddField(
            model_name="target",
            name="type",
            field=models.CharField(
                choices=[
                    ("Science", "Science Target"),
                    ("Calibration", "Calibration Target"),
                ],
                default="Science",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="scienceresult",
            name="author",
        ),
        migrations.AlterField(
            model_name="target",
            name="source",
            field=models.CharField(
                help_text="How target was identified or discovered", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="Observer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.observation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tom.person"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scienceresult",
            name="author",
            field=models.CharField(default="", max_length=200),
        ),
    ]
