# Generated by Django 4.2.7 on 2024-01-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0012_remove_sciencetarget_calibrations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scienceresult",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="SpectrumEvaluation",
            fields=[
                (
                    "scienceresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tom.scienceresult",
                    ),
                ),
                (
                    "quality",
                    models.FloatField(default=0, help_text="Scale of 5 with 5 highest"),
                ),
                ("comment", models.CharField(max_length=200)),
                (
                    "spectrum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.spectrumrawdata",
                    ),
                ),
            ],
            bases=("tom.scienceresult",),
        ),
        migrations.CreateModel(
            name="SpeckleResolution",
            fields=[
                (
                    "scienceresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tom.scienceresult",
                    ),
                ),
                ("coords", models.CharField(max_length=50)),
                ("filename", models.CharField(default="", max_length=50)),
                ("epoch", models.FloatField(default=0)),
                ("chi_sq", models.FloatField(default=0)),
                ("seeing", models.FloatField(default=0)),
                ("position_angle", models.FloatField(default=0)),
                ("separation", models.FloatField(default=0)),
                ("delta_mag", models.FloatField(default=0)),
                ("filter", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(max_length=100)),
                (
                    "speckle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tom.specklerawdata",
                    ),
                ),
            ],
            bases=("tom.scienceresult",),
        ),
    ]
