# Generated by Django 4.2.7 on 2024-01-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0013_alter_scienceresult_type_spectrumevaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speckleresolution",
            name="coords",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="speckleresolution",
            name="notes",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="spectrumevaluation",
            name="comment",
            field=models.CharField(default="", max_length=200),
        ),
    ]
