# Generated by Django 4.2.7 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0013_alter_observatory_options_alter_otherrawdata_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="magnitude",
            field=models.FloatField(default=0),
        ),
    ]
