# Generated by Django 4.2.7 on 2023-11-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0014_target_magnitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="target",
        ),
        migrations.RemoveField(
            model_name="target",
            name="calibrations",
        ),
        migrations.RemoveField(
            model_name="target",
            name="type",
        ),
        migrations.AddField(
            model_name="observation",
            name="observers",
            field=models.ManyToManyField(to="tom.person"),
        ),
        migrations.AlterField(
            model_name="scienceresult",
            name="type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="target",
            name="distance",
            field=models.FloatField(default=0, verbose_name="Distance (pc)"),
        ),
        migrations.AlterField(
            model_name="target",
            name="magnitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="target",
            name="pmdec",
            field=models.FloatField(default=0, verbose_name="PM Dec (mas/yr)"),
        ),
        migrations.AlterField(
            model_name="target",
            name="pmra",
            field=models.FloatField(default=0, verbose_name="PM RA (mas/yr)"),
        ),
        migrations.AlterField(
            model_name="target",
            name="source",
            field=models.CharField(
                help_text="How target was identified/discovered", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="CalibrationTarget",
            fields=[
                (
                    "target_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tom.target",
                    ),
                ),
                ("type", models.CharField(default="", max_length=50)),
            ],
            bases=("tom.target",),
        ),
        migrations.CreateModel(
            name="ScienceTarget",
            fields=[
                (
                    "target_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tom.target",
                    ),
                ),
                ("calibrations", models.ManyToManyField(to="tom.calibrationtarget")),
            ],
            bases=("tom.target",),
        ),
        migrations.DeleteModel(
            name="Observer",
        ),
    ]
