# Generated by Django 4.2.7 on 2024-01-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0015_tess_ticv8_gaia_dr3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="dec",
        ),
        migrations.RemoveField(
            model_name="target",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="target",
            name="magnitude",
        ),
        migrations.RemoveField(
            model_name="target",
            name="pmdec",
        ),
        migrations.RemoveField(
            model_name="target",
            name="pmra",
        ),
        migrations.RemoveField(
            model_name="target",
            name="ra",
        ),
        migrations.AddField(
            model_name="target",
            name="target_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="CatalogAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog",
                    models.CharField(
                        help_text="Name of associated catalog", max_length=100
                    ),
                ),
                (
                    "catalog_id",
                    models.CharField(
                        help_text="Identifier within associated catalog", max_length=100
                    ),
                ),
                (
                    "association",
                    models.CharField(
                        help_text="Reason for association with catalog object",
                        max_length=100,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tom.target"
                    ),
                ),
            ],
        ),
    ]
