# Generated by Django 4.2.7 on 2023-11-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0015_remove_observation_target_remove_target_calibrations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="target",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tom.target"
            ),
            preserve_default=False,
        ),
    ]
