# Generated by Django 4.2.7 on 2024-01-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0016_remove_target_dec_remove_target_distance_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScienceTarget",
        ),
    ]
