# Generated by Django 4.2.7 on 2023-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0016_observation_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="gaia_id",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="target",
            name="source",
            field=models.CharField(
                default="",
                help_text="How target was identified/discovered",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="tic_id",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.CreateModel(
            name="TargetList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("targets", models.ManyToManyField(to="tom.target")),
            ],
        ),
    ]
