# Generated by Django 4.2.7 on 2023-11-21 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0017_alter_target_gaia_id_alter_target_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibrationtarget",
            name="type",
        ),
    ]
