# Generated by Django 4.2.7 on 2024-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0020_alter_gaia_dr2_tic_distance_alter_gaia_dr2_tic_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gaia_dr2",
            name="DESIGNATION",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="a_g_percentile_lower",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="a_g_percentile_upper",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="a_g_val",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="astrometric_primary_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="astrometric_pseudo_colour",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="astrometric_pseudo_colour_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="bp_g",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="bp_rp",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="datalink_url",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="dec_parallax_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="dec_pmdec_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="dec_pmra_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="duplicated_source",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="e_bp_min_rp_percentile_lower",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="e_bp_min_rp_percentile_upper",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="e_bp_min_rp_val",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="epoch_photometry_url",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="flame_flags",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="g_rp",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="lum_percentile_lower",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="lum_percentile_upper",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="lum_val",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="parallax",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="parallax_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="parallax_over_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="parallax_pmdec_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="parallax_pmra_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_bp_mean_flux",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_bp_mean_flux_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_bp_mean_flux_over_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_bp_mean_mag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_bp_rp_excess_factor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_rp_mean_flux",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_rp_mean_flux_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_rp_mean_flux_over_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_rp_mean_mag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="phot_variable_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="pmdec",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="pmdec_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="pmra",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="pmra_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="pmra_pmdec_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="priam_flags",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="ra_parallax_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="ra_pmdec_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="ra_pmra_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="radial_velocity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="radial_velocity_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="radius_percentile_lower",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="radius_percentile_upper",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="radius_val",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="rv_template_fe_h",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="rv_template_logg",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="rv_template_teff",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="teff_percentile_lower",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="teff_percentile_upper",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr2",
            name="teff_val",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="DESIGNATION",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="astrometric_primary_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="dec_pseudocolour_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="duplicated_source",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_epoch_photometry",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_epoch_rv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_mcmc_gspphot",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_mcmc_msc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_rvs",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_xp_continuous",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="has_xp_sampled",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="in_andromeda_survey",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="in_galaxy_candidates",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="in_qso_candidates",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="libname_gspphot",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="parallax_pseudocolour_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="phot_variable_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="pmdec_pseudocolour_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="pmra_pseudocolour_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="pseudocolour",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="pseudocolour_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="ra_pseudocolour_corr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="rv_amplitude_robust",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="rv_chisq_pvalue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="rv_renormalised_gof",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="rvs_spec_sig_to_noise",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="vbroad",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="vbroad_error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gaia_dr3",
            name="vbroad_nb_transits",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="ALLWISE",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="APASS",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="BmagFlag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="EBVflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="GAIA",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="HIP",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="KIC",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="PARflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="PMflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="POSflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="SDSS",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="SPFlag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="TESSflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="TWOMASS",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="TWOMflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="TYC",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="Teff",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="TeffFlag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="UCAC",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="VmagFlag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="disposition",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="distflag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="lumclass",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="objType",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tess_ticv8",
            name="typeSrc",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
