# Generated by Django 4.2.7 on 2024-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0021_alter_gaia_dr2_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tess_ticv8",
            name="Tess_TICv8",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
