# Generated by Django 4.2.7 on 2024-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0023_rename_tess_ticv8_tess_ticv8_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tess_ticv8",
            name="Identifier",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
