# Generated by Django 4.2.7 on 2024-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0027_binaryparameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryparameters",
            name="period",
            field=models.FloatField(help_text="Period in days", null=True),
        ),
        migrations.AlterField(
            model_name="binaryparameters",
            name="t0_primary",
            field=models.FloatField(help_text="Date in BJD", null=True),
        ),
    ]
