# Generated by Django 4.2.7 on 2024-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0028_alter_binaryparameters_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryparameters",
            name="duration_primary",
            field=models.FloatField(help_text="Duration in hours", null=True),
        ),
    ]
