# Generated by Django 4.2.7 on 2024-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0029_alter_binaryparameters_duration_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="depth_primary",
            new_name="depth_a",
        ),
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="depth_secondary",
            new_name="depth_b",
        ),
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="duration_primary",
            new_name="duration_a",
        ),
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="duration_secondary",
            new_name="duration_b",
        ),
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="t0_primary",
            new_name="t0_a",
        ),
        migrations.RenameField(
            model_name="binaryparameters",
            old_name="t0_secondary",
            new_name="t0_b",
        ),
        migrations.AlterField(
            model_name="binaryparameters",
            name="member",
            field=models.CharField(
                help_text="Name of component, eg A, B, C", max_length=50
            ),
        ),
    ]
