# Generated by Django 4.2.7 on 2024-02-25 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tom", "0030_rename_depth_primary_binaryparameters_depth_a_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="local_id",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="target",
            old_name="target_type",
            new_name="type",
        ),
    ]
