# Generated by Django 5.1.1 on 2024-10-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0031_rename_local_id_target_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binaryparameters',
            old_name='depth_a',
            new_name='depth',
        ),
        migrations.RenameField(
            model_name='binaryparameters',
            old_name='duration_a',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='binaryparameters',
            old_name='t0_a',
            new_name='t0',
        ),
        migrations.RemoveField(
            model_name='binaryparameters',
            name='depth_b',
        ),
        migrations.RemoveField(
            model_name='binaryparameters',
            name='duration_b',
        ),
        migrations.RemoveField(
            model_name='binaryparameters',
            name='t0_b',
        ),
    ]
