# Generated by Django 5.1.1 on 2024-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0032_rename_depth_a_binaryparameters_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryparameters',
            name='system',
            field=models.CharField(default='', help_text='Name of system/pair, eg A, B, C', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='binaryparameters',
            name='member',
            field=models.CharField(help_text='Name of component of system, eg a, b, c', max_length=50),
        ),
    ]
