from django.db import models

class Gaia_DR3(models.Model):
    solution_id = models.BigIntegerField(null=True)
    DESIGNATION = models.CharField(max_length=100, null=True, unique=True)
    source_id = models.CharField(max_length=100, null=True, unique=True)
    random_index = models.BigIntegerField(null=True)
    ref_epoch = models.FloatField(null=True)
    ra = models.FloatField(null=True)
    ra_error = models.FloatField(null=True)
    dec = models.FloatField(null=True)
    dec_error = models.FloatField(null=True)
    parallax = models.FloatField(null=True)
    parallax_error = models.FloatField(null=True)
    parallax_over_error = models.FloatField(null=True)
    pm = models.FloatField(null=True)
    pmra = models.FloatField(null=True)
    pmra_error = models.FloatField(null=True)
    pmdec = models.FloatField(null=True)
    pmdec_error = models.FloatField(null=True)
    ra_dec_corr = models.FloatField(null=True)
    ra_parallax_corr = models.FloatField(null=True)
    ra_pmra_corr = models.FloatField(null=True)
    ra_pmdec_corr = models.FloatField(null=True)
    dec_parallax_corr = models.FloatField(null=True)
    dec_pmra_corr = models.FloatField(null=True)
    dec_pmdec_corr = models.FloatField(null=True)
    parallax_pmra_corr = models.FloatField(null=True)
    parallax_pmdec_corr = models.FloatField(null=True)
    pmra_pmdec_corr = models.FloatField(null=True)
    astrometric_n_obs_al = models.IntegerField(null=True)
    astrometric_n_obs_ac = models.IntegerField(null=True)
    astrometric_n_good_obs_al = models.IntegerField(null=True)
    astrometric_n_bad_obs_al = models.IntegerField(null=True)
    astrometric_gof_al = models.FloatField(null=True)
    astrometric_chi2_al = models.FloatField(null=True)
    astrometric_excess_noise = models.FloatField(null=True)
    astrometric_excess_noise_sig = models.FloatField(null=True)
    astrometric_params_solved = models.IntegerField(null=True)
    astrometric_primary_flag = models.CharField(max_length=100, null=True)
    nu_eff_used_in_astrometry = models.FloatField(null=True)
    pseudocolour = models.CharField(max_length=100, null=True)
    pseudocolour_error = models.CharField(max_length=100, null=True)
    ra_pseudocolour_corr = models.CharField(max_length=100, null=True)
    dec_pseudocolour_corr = models.CharField(max_length=100, null=True)
    parallax_pseudocolour_corr = models.CharField(max_length=100, null=True)
    pmra_pseudocolour_corr = models.CharField(max_length=100, null=True)
    pmdec_pseudocolour_corr = models.CharField(max_length=100, null=True)
    astrometric_matched_transits = models.IntegerField(null=True)
    visibility_periods_used = models.IntegerField(null=True)
    astrometric_sigma5d_max = models.FloatField(null=True)
    matched_transits = models.IntegerField(null=True)
    new_matched_transits = models.IntegerField(null=True)
    matched_transits_removed = models.IntegerField(null=True)
    ipd_gof_harmonic_amplitude = models.FloatField(null=True)
    ipd_gof_harmonic_phase = models.FloatField(null=True)
    ipd_frac_multi_peak = models.IntegerField(null=True)
    ipd_frac_odd_win = models.IntegerField(null=True)
    ruwe = models.FloatField(null=True)
    scan_direction_strength_k1 = models.FloatField(null=True)
    scan_direction_strength_k2 = models.FloatField(null=True)
    scan_direction_strength_k3 = models.FloatField(null=True)
    scan_direction_strength_k4 = models.FloatField(null=True)
    scan_direction_mean_k1 = models.FloatField(null=True)
    scan_direction_mean_k2 = models.FloatField(null=True)
    scan_direction_mean_k3 = models.FloatField(null=True)
    scan_direction_mean_k4 = models.FloatField(null=True)
    duplicated_source = models.CharField(max_length=100, null=True)
    phot_g_n_obs = models.IntegerField(null=True)
    phot_g_mean_flux = models.FloatField(null=True)
    phot_g_mean_flux_error = models.FloatField(null=True)
    phot_g_mean_flux_over_error = models.FloatField(null=True)
    phot_g_mean_mag = models.FloatField(null=True)
    phot_bp_n_obs = models.IntegerField(null=True)
    phot_bp_mean_flux = models.FloatField(null=True)
    phot_bp_mean_flux_error = models.FloatField(null=True)
    phot_bp_mean_flux_over_error = models.FloatField(null=True)
    phot_bp_mean_mag = models.FloatField(null=True)
    phot_rp_n_obs = models.IntegerField(null=True)
    phot_rp_mean_flux = models.FloatField(null=True)
    phot_rp_mean_flux_error = models.FloatField(null=True)
    phot_rp_mean_flux_over_error = models.FloatField(null=True)
    phot_rp_mean_mag = models.FloatField(null=True)
    phot_bp_rp_excess_factor = models.FloatField(null=True)
    phot_bp_n_contaminated_transits = models.IntegerField(null=True)
    phot_bp_n_blended_transits = models.IntegerField(null=True)
    phot_rp_n_contaminated_transits = models.IntegerField(null=True)
    phot_rp_n_blended_transits = models.IntegerField(null=True)
    phot_proc_mode = models.IntegerField(null=True)
    bp_rp = models.FloatField(null=True)
    bp_g = models.FloatField(null=True)
    g_rp = models.FloatField(null=True)
    radial_velocity = models.FloatField(null=True)
    radial_velocity_error = models.FloatField(null=True)
    rv_method_used = models.IntegerField(null=True)
    rv_nb_transits = models.IntegerField(null=True)
    rv_nb_deblended_transits = models.IntegerField(null=True)
    rv_visibility_periods_used = models.IntegerField(null=True)
    rv_expected_sig_to_noise = models.FloatField(null=True)
    rv_renormalised_gof = models.CharField(max_length=100, null=True)
    rv_chisq_pvalue = models.CharField(max_length=100, null=True)
    rv_time_duration = models.FloatField(null=True)
    rv_amplitude_robust = models.CharField(max_length=100, null=True)
    rv_template_teff = models.FloatField(null=True)
    rv_template_logg = models.FloatField(null=True)
    rv_template_fe_h = models.FloatField(null=True)
    rv_atm_param_origin = models.IntegerField(null=True)
    vbroad = models.CharField(max_length=100, null=True)
    vbroad_error = models.CharField(max_length=100, null=True)
    vbroad_nb_transits = models.CharField(max_length=100, null=True)
    grvs_mag = models.FloatField(null=True)
    grvs_mag_error = models.FloatField(null=True)
    grvs_mag_nb_transits = models.IntegerField(null=True)
    rvs_spec_sig_to_noise = models.CharField(max_length=100, null=True)
    phot_variable_flag = models.CharField(max_length=100, null=True)
    l = models.FloatField(null=True)
    b = models.FloatField(null=True)
    ecl_lon = models.FloatField(null=True)
    ecl_lat = models.FloatField(null=True)
    in_qso_candidates = models.CharField(max_length=100, null=True)
    in_galaxy_candidates = models.CharField(max_length=100, null=True)
    non_single_star = models.IntegerField(null=True)
    has_xp_continuous = models.CharField(max_length=100, null=True)
    has_xp_sampled = models.CharField(max_length=100, null=True)
    has_rvs = models.CharField(max_length=100, null=True)
    has_epoch_photometry = models.CharField(max_length=100, null=True)
    has_epoch_rv = models.CharField(max_length=100, null=True)
    has_mcmc_gspphot = models.CharField(max_length=100, null=True)
    has_mcmc_msc = models.CharField(max_length=100, null=True)
    in_andromeda_survey = models.CharField(max_length=100, null=True)
    classprob_dsc_combmod_quasar = models.FloatField(null=True)
    classprob_dsc_combmod_galaxy = models.FloatField(null=True)
    classprob_dsc_combmod_star = models.FloatField(null=True)
    teff_gspphot = models.FloatField(null=True)
    teff_gspphot_lower = models.FloatField(null=True)
    teff_gspphot_upper = models.FloatField(null=True)
    logg_gspphot = models.FloatField(null=True)
    logg_gspphot_lower = models.FloatField(null=True)
    logg_gspphot_upper = models.FloatField(null=True)
    mh_gspphot = models.FloatField(null=True)
    mh_gspphot_lower = models.FloatField(null=True)
    mh_gspphot_upper = models.FloatField(null=True)
    distance_gspphot = models.FloatField(null=True)
    distance_gspphot_lower = models.FloatField(null=True)
    distance_gspphot_upper = models.FloatField(null=True)
    azero_gspphot = models.FloatField(null=True)
    azero_gspphot_lower = models.FloatField(null=True)
    azero_gspphot_upper = models.FloatField(null=True)
    ag_gspphot = models.FloatField(null=True)
    ag_gspphot_lower = models.FloatField(null=True)
    ag_gspphot_upper = models.FloatField(null=True)
    ebpminrp_gspphot = models.FloatField(null=True)
    ebpminrp_gspphot_lower = models.FloatField(null=True)
    ebpminrp_gspphot_upper = models.FloatField(null=True)
    libname_gspphot = models.CharField(max_length=100, null=True)
    TIC_ID = models.IntegerField(null=True)
    TIC_Distance = models.FloatField(null=True)
