from django.db import models

class Tess_TICv8(models.Model):
    Identifier = models.CharField(max_length=100, null=True, unique=True)
    version = models.IntegerField(null=True)
    HIP = models.CharField(max_length=100, null=True)
    TYC = models.CharField(max_length=100, null=True)
    UCAC = models.CharField(max_length=100, null=True)
    TWOMASS = models.CharField(max_length=100, null=True)
    SDSS = models.CharField(max_length=100, null=True)
    ALLWISE = models.CharField(max_length=100, null=True)
    GAIA = models.CharField(max_length=100, null=True)
    APASS = models.CharField(max_length=100, null=True)
    KIC = models.CharField(max_length=100, null=True)
    objType = models.CharField(max_length=100, null=True)
    typeSrc = models.CharField(max_length=100, null=True)
    ra = models.FloatField(null=True)
    dec = models.FloatField(null=True)
    POSflag = models.CharField(max_length=100, null=True)
    pmRA = models.FloatField(null=True)
    e_pmRA = models.FloatField(null=True)
    pmDEC = models.FloatField(null=True)
    e_pmDEC = models.FloatField(null=True)
    PMflag = models.CharField(max_length=100, null=True)
    plx = models.FloatField(null=True)
    e_plx = models.FloatField(null=True)
    PARflag = models.CharField(max_length=100, null=True)
    gallong = models.FloatField(null=True)
    gallat = models.FloatField(null=True)
    eclong = models.FloatField(null=True)
    eclat = models.FloatField(null=True)
    Bmag = models.FloatField(null=True)
    e_Bmag = models.FloatField(null=True)
    Vmag = models.FloatField(null=True)
    e_Vmag = models.FloatField(null=True)
    umag = models.FloatField(null=True)
    e_umag = models.FloatField(null=True)
    gmag = models.FloatField(null=True)
    e_gmag = models.FloatField(null=True)
    rmag = models.FloatField(null=True)
    e_rmag = models.FloatField(null=True)
    imag = models.FloatField(null=True)
    e_imag = models.FloatField(null=True)
    zmag = models.FloatField(null=True)
    e_zmag = models.FloatField(null=True)
    Jmag = models.FloatField(null=True)
    e_Jmag = models.FloatField(null=True)
    Hmag = models.FloatField(null=True)
    e_Hmag = models.FloatField(null=True)
    Kmag = models.FloatField(null=True)
    e_Kmag = models.FloatField(null=True)
    TWOMflag = models.CharField(max_length=100, null=True)
    prox = models.FloatField(null=True)
    w1mag = models.FloatField(null=True)
    e_w1mag = models.FloatField(null=True)
    w2mag = models.FloatField(null=True)
    e_w2mag = models.FloatField(null=True)
    w3mag = models.FloatField(null=True)
    e_w3mag = models.FloatField(null=True)
    w4mag = models.FloatField(null=True)
    e_w4mag = models.FloatField(null=True)
    GAIAmag = models.FloatField(null=True)
    e_GAIAmag = models.FloatField(null=True)
    Tmag = models.FloatField(null=True)
    e_Tmag = models.FloatField(null=True)
    TESSflag = models.CharField(max_length=100, null=True)
    SPFlag = models.CharField(max_length=100, null=True)
    Teff = models.FloatField(null=True)
    e_Teff = models.FloatField(null=True)
    logg = models.FloatField(null=True)
    e_logg = models.FloatField(null=True)
    MH = models.FloatField(null=True)
    e_MH = models.FloatField(null=True)
    rad = models.FloatField(null=True)
    e_rad = models.FloatField(null=True)
    mass = models.FloatField(null=True)
    e_mass = models.FloatField(null=True)
    rho = models.FloatField(null=True)
    e_rho = models.FloatField(null=True)
    lumclass = models.CharField(max_length=100, null=True)
    lum = models.FloatField(null=True)
    e_lum = models.FloatField(null=True)
    d = models.FloatField(null=True)
    e_d = models.FloatField(null=True)
    ebv = models.FloatField(null=True)
    e_ebv = models.FloatField(null=True)
    numcont = models.IntegerField(null=True)
    contratio = models.FloatField(null=True)
    disposition = models.CharField(max_length=100, null=True)
    duplicate_id = models.BigIntegerField(null=True)
    priority = models.FloatField(null=True)
    eneg_EBV = models.FloatField(null=True)
    epos_EBV = models.FloatField(null=True)
    EBVflag = models.CharField(max_length=100, null=True)
    eneg_Mass = models.FloatField(null=True)
    epos_Mass = models.FloatField(null=True)
    eneg_Rad = models.FloatField(null=True)
    epos_Rad = models.FloatField(null=True)
    eneg_rho = models.FloatField(null=True)
    epos_rho = models.FloatField(null=True)
    eneg_logg = models.FloatField(null=True)
    epos_logg = models.FloatField(null=True)
    eneg_lum = models.FloatField(null=True)
    epos_lum = models.FloatField(null=True)
    eneg_dist = models.FloatField(null=True)
    epos_dist = models.FloatField(null=True)
    distflag = models.CharField(max_length=100, null=True)
    eneg_Teff = models.FloatField(null=True)
    epos_Teff = models.FloatField(null=True)
    TeffFlag = models.CharField(max_length=100, null=True)
    gaiabp = models.FloatField(null=True)
    e_gaiabp = models.FloatField(null=True)
    gaiarp = models.FloatField(null=True)
    e_gaiarp = models.FloatField(null=True)
    gaiaqflag = models.IntegerField(null=True)
    starchareFlag = models.IntegerField(null=True)
    VmagFlag = models.CharField(max_length=100, null=True)
    BmagFlag = models.CharField(max_length=100, null=True)
    splists = models.IntegerField(null=True)
    e_RA = models.FloatField(null=True)
    e_Dec = models.FloatField(null=True)
    RA_orig = models.FloatField(null=True)
    Dec_orig = models.FloatField(null=True)
    e_RA_orig = models.FloatField(null=True)
    e_Dec_orig = models.FloatField(null=True)
    raddflag = models.IntegerField(null=True)
    wdflag = models.IntegerField(null=True)
    objID = models.BigIntegerField(null=True)
