from django.db import models

class Tess_TICv8(models.Model):
    target = models.ForeignKey("Target", on_delete=models.CASCADE)
    Tess_TICv8 = models.IntegerField()
    version = models.IntegerField()
    HIP = models.CharField(max_length=100, default="")
    TYC = models.CharField(max_length=100, default="")
    UCAC = models.CharField(max_length=100, default="")
    TWOMASS = models.CharField(max_length=100, default="")
    SDSS = models.CharField(max_length=100, default="")
    ALLWISE = models.CharField(max_length=100, default="")
    GAIA = models.BigIntegerField()
    APASS = models.IntegerField()
    KIC = models.CharField(max_length=100, default="")
    objType = models.CharField(max_length=100, default="")
    typeSrc = models.CharField(max_length=100, default="")
    ra = models.FloatField()
    dec = models.FloatField()
    POSflag = models.CharField(max_length=100, default="")
    pmRA = models.FloatField()
    e_pmRA = models.FloatField()
    pmDEC = models.FloatField()
    e_pmDEC = models.FloatField()
    PMflag = models.CharField(max_length=100, default="")
    plx = models.FloatField()
    e_plx = models.FloatField()
    PARflag = models.CharField(max_length=100, default="")
    gallong = models.FloatField()
    gallat = models.FloatField()
    eclong = models.FloatField()
    eclat = models.FloatField()
    Bmag = models.FloatField()
    e_Bmag = models.FloatField()
    Vmag = models.FloatField()
    e_Vmag = models.FloatField()
    umag = models.IntegerField()
    e_umag = models.IntegerField()
    gmag = models.IntegerField()
    e_gmag = models.IntegerField()
    rmag = models.IntegerField()
    e_rmag = models.IntegerField()
    imag = models.IntegerField()
    e_imag = models.IntegerField()
    zmag = models.IntegerField()
    e_zmag = models.IntegerField()
    Jmag = models.FloatField()
    e_Jmag = models.FloatField()
    Hmag = models.FloatField()
    e_Hmag = models.FloatField()
    Kmag = models.FloatField()
    e_Kmag = models.FloatField()
    TWOMflag = models.CharField(max_length=100, default="")
    prox = models.IntegerField()
    w1mag = models.FloatField()
    e_w1mag = models.FloatField()
    w2mag = models.FloatField()
    e_w2mag = models.FloatField()
    w3mag = models.FloatField()
    e_w3mag = models.FloatField()
    w4mag = models.FloatField()
    e_w4mag = models.IntegerField()
    GAIAmag = models.FloatField()
    e_GAIAmag = models.FloatField()
    Tmag = models.FloatField()
    e_Tmag = models.FloatField()
    TESSflag = models.CharField(max_length=100, default="")
    SPFlag = models.CharField(max_length=100, default="")
    Teff = models.FloatField()
    e_Teff = models.FloatField()
    logg = models.FloatField()
    e_logg = models.IntegerField()
    MH = models.FloatField()
    e_MH = models.FloatField()
    rad = models.FloatField()
    e_rad = models.IntegerField()
    mass = models.FloatField()
    e_mass = models.IntegerField()
    rho = models.FloatField()
    e_rho = models.IntegerField()
    lumclass = models.CharField(max_length=100, default="")
    lum = models.FloatField()
    e_lum = models.IntegerField()
    d = models.FloatField()
    e_d = models.FloatField()
    ebv = models.FloatField()
    e_ebv = models.IntegerField()
    numcont = models.CharField(max_length=100, default="")
    contratio = models.IntegerField()
    disposition = models.CharField(max_length=100, default="")
    duplicate_id = models.CharField(max_length=100, default="")
    priority = models.IntegerField()
    eneg_EBV = models.IntegerField()
    epos_EBV = models.IntegerField()
    EBVflag = models.CharField(max_length=100, default="")
    eneg_Mass = models.IntegerField()
    epos_Mass = models.IntegerField()
    eneg_Rad = models.IntegerField()
    epos_Rad = models.IntegerField()
    eneg_rho = models.IntegerField()
    epos_rho = models.IntegerField()
    eneg_logg = models.IntegerField()
    epos_logg = models.IntegerField()
    eneg_lum = models.IntegerField()
    epos_lum = models.IntegerField()
    eneg_dist = models.IntegerField()
    epos_dist = models.IntegerField()
    distflag = models.CharField(max_length=100, default="")
    eneg_Teff = models.IntegerField()
    epos_Teff = models.IntegerField()
    TeffFlag = models.CharField(max_length=100, default="")
    gaiabp = models.FloatField()
    e_gaiabp = models.FloatField()
    gaiarp = models.FloatField()
    e_gaiarp = models.FloatField()
    gaiaqflag = models.IntegerField()
    starchareFlag = models.CharField(max_length=100, default="")
    VmagFlag = models.CharField(max_length=100, default="")
    BmagFlag = models.CharField(max_length=100, default="")
    splists = models.CharField(max_length=100, default="")
    e_RA = models.FloatField()
    e_Dec = models.FloatField()
    RA_orig = models.FloatField()
    Dec_orig = models.FloatField()
    e_RA_orig = models.FloatField()
    e_Dec_orig = models.FloatField()
    raddflag = models.IntegerField()
    wdflag = models.IntegerField()
    objID = models.IntegerField()
